import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./_context/AuthContext";
import SocketContextProvider from "./_context/SocketContext";
import ReduxProvider from "../redux/ReduxProvider";
import { Toaster } from "react-hot-toast";
import Userunread from "./_context/Userunread";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthContextProvider>
            <SocketContextProvider>
              <Userunread>
                <div className="h-screen flex items-center justify-center">
                  {children}
                </div>
              </Userunread>
            </SocketContextProvider>
          </AuthContextProvider>
        </ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
